#!/usr/bin/env bash
# Creates a redirection

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start Nginx service
sudo service nginx start

# Create a configuration file for the redirection
echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 esianyo.tech;
    }
}" | sudo tee /etc/nginx/sites-available/redirection

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/

# Remove the default configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx service to apply the changes
sudo service nginx restart
