#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Install Nginx (if not already installed)
apt-get update
apt-get install -y nginx

# Ensure Nginx is running
service nginx start

# Check the status of Nginx
service nginx status

# Configure Nginx to listen on port 80 for all active IPv4 IPs
sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
