#!/usr/bin/env bash
# debugging nginx connection

#!/usr/bin/env bash
# This script fixes Nginx to listen on port 80

apt-get update
apt-get install -y nginx
service nginx start
sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default
service nginx restart
